name: CI
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint:strict

  typecheck:
    name: TypeScript type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: TypeCheck core
        run: pnpm --filter "@mcpify/core" typecheck
      - name: TypeCheck demo
        run: pnpm --filter "@mcpify/demo" typecheck
      - name: TypeCheck tests
        run: pnpm --filter "@mcpify/tests" typecheck

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test
      - name: Run tests with coverage
        run: pnpm test:coverage
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
